# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord-sqlserver-adapter'
gem 'awesome_print'
gem 'aws-sdk-bedrockruntime'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-transcribeservice'
gem 'concurrent-ruby', require: 'concurrent'
gem 'csv'
gem 'docx'
gem 'dotenv'
gem 'faraday'
gem 'httparty'
gem 'json', '2.10.2'
gem 'nokogiri'
gem 'open-uri'
gem 'ostruct'
gem 'pdf-reader'
gem 'pg'
gem 'puma'
gem 'rack'
gem 'rackup'
gem 'rails'
gem 'rubocop'
gem 'ruby-lsp'
gem 'sidekiq'
gem 'streamio-ffmpeg'
gem 'stringio'
gem 'watir'
